version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  build:
    working_directory: ~/in_the_field_be
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          RAILS_ENV: test
          RACK_ENV: test
      - image: postgres:14.7
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: in_the_field_be_test
          POSTGRES_PASSWORD:
    executor: ruby/default   
    steps:
      - checkout
      - run:
          name: in_the_field_be
          command: bundle -v
      - checkout
      - run: bundle config set --local path 'vendor/bundle'
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Database Setup
          command: bin/rails db:{create,migrate} --trace
      - run:
          name: Run Tests
          command: bundle exec rspec    
      # - checkout
      # - run: 
      #     name: push to render
      #     command: git push render main 
     
     

     
