version: 2.1

orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  build:
    # working_directory: ~/In_The_Field_BE
    docker:
      - image: cimg/ruby:3.2.2
        environment:
          PGHOST: 127.0.0.1
          PGUSER: in_the_field_be
          RAILS_ENV: test
          # RACK_ENV: test
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: in_the_field_be_test
          POSTGRES_PASSWORD: secret
    executor: ruby/default   
    steps:
      - checkout
      - run:
          name: in_the_field_be
          command: bundle -v
      - checkout
      - run:
          name: Force Bundler Version
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run: bundle config set --local path 'vendor/bundle'
      - run:
          name: bundle install
          command: bundle install
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database Setup
          command: bin/rails db:{create,migrate} --trace
      - run:
          name: Run Tests
          command: bundle exec rspec 
workflows:
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main   
      # - checkout
      # - run: 
      #     name: push to render
      #     command: git push render main 
     
     

     
